repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
#=======
#---
#repos:
#  - hooks:
#      - id: trailing-whitespace
#      - id: end-of-file-fixer
#      - id: check-yaml
#      - id: check-added-large-files
#    repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.4.0
#
#  - hooks:
#      - id: black
#    repo: https://github.com/ambv/black
#    rev: 23.1.0
#
#  - hooks:
#      - id: prettier
#        types_or: [css, javascript, markdown, scss, yaml, gitignore, toml]
#    repo: https://github.com/pre-commit/mirrors-prettier
#    rev: v3.0.0-alpha.4
#
#  # - hooks:
#  #     - additional_dependencies:
#  #         - flake8-bugbear
#  #         - flake8-comprehensions
#  #         - flake8-mutable
#  #         - flake8-print
#  #         - flake8-simplify
#  #       id: flake8
#  #   repo: https://github.com/pycqa/flake8
#  #   rev: 6.0.0
#  #
#  # - hooks:
#  #     - id: djlint-django
#  #   repo: https://github.com/Riverside-Healthcare/djLint
#  #   rev: v1.19.15
#>>>>>>> aeaeb9b774e53fa22c3df01cbbd9ef199f3fc17c
