# Generated by Django 4.1 on 2023-10-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("dra", "Draft"), ("pri", "Private"), ("pub", "Published")],
                default="pub",
                max_length=10,
            ),
        ),
    ]
