# Generated by Django 4.1 on 2023-01-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_date_completed_item_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='completed',
            new_name='complete',
        ),
    ]
