# Generated by Django 4.1 on 2022-11-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='childhood_hobbies',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_mbti',
            field=models.CharField(blank=True, choices=[('TBD', 'To Be Determined'), ('INFP', 'INFP'), ('INFJ', 'INFJ'), ('INTP', 'INTP'), ('INTJ', 'INTJ'), ('ISFP', 'ISFP'), ('ISFJ', 'ISFJ'), ('ISTP', 'ISTP'), ('ISTJ', 'ISTJ'), ('ENFP', 'ENFP'), ('ENFJ', 'ENFJ'), ('ENTP', 'ENTP'), ('ENTJ', 'ENTJ'), ('ESFP', 'ESFP'), ('ESFJ', 'ESFJ'), ('ESTP', 'ESTP'), ('ESTJ', 'ESTJ')], default=None, max_length=4, null=True),
        ),
    ]
