# Generated by Django 4.1 on 2022-12-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_todolist_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='deadline',
        ),
    ]
