# Generated by Django 4.1 on 2023-02-19 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tarotcard_deck_tarotcard_number_alter_deck_deck_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.deck'),
        ),
    ]
