# Generated by Django 4.1 on 2023-02-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_tarotcard_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcard',
            name='description',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarotcard',
            name='keywords',
            field=models.TextField(default='default keywords'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarotcard',
            name='name',
            field=models.CharField(default='name', max_length=30),
            preserve_default=False,
        ),
    ]
