# Generated by Django 4.1 on 2023-01-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_item_author_alter_todolist_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zodiac',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
