# Generated by Django 4.1 on 2023-02-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tarotcard_description_tarotcard_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarotcard',
            name='element',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarotcard',
            name='question',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarotcard',
            name='reverse',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarotcard',
            name='upright',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
