# Generated by Django 4.1 on 2023-02-23 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_tarotcard_element_tarotcard_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='TarotAnswer',
        ),
        migrations.DeleteModel(
            name='TarotRating',
        ),
        migrations.DeleteModel(
            name='TarotRequest',
        ),
        migrations.RenameModel(
            old_name='TarotCard',
            new_name='Card',
        ),
        migrations.AddField(
            model_name='readrequest',
            name='card_ids',
            field=models.ManyToManyField(to='home.card'),
        ),
        migrations.AddField(
            model_name='readrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
