# Generated by Django 4.1 on 2023-01-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_profile_zodiac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zodiac',
            field=models.CharField(default='blah', max_length=20),
        ),
    ]
