# Generated by Django 4.1 on 2023-02-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_readrequest_delete_tarotanswer_delete_tarotrating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readrequest',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
