# Generated by Django 4.1 on 2023-02-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_readrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='readrequest',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
