# Generated by Django 4.1 on 2023-03-03 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_readrequest_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readrequest',
            name='card_ids',
            field=models.ManyToManyField(default=0, to='home.card'),
        ),
        migrations.AlterField(
            model_name='readrequest',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
