# Generated by Django 4.1 on 2022-12-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_item_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='author',
        ),
    ]
